name: pwn-request
on:
  pull_request_target:
    types: [labeled]
permissions: write-all
jobs:
  build:
    if: github.event.label.name == 'never-applied'
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "${{ github.event.pull_request.title }}"
